### ISSUE TITLE
 How to change the image size to 600X600? The Qo-DL-R5d is the largest size.

### ISSUE THREAD

**Issue by zzxhll** [Sorrow446/Qo-DL#100]
How to change the image size to 600X600? The Qo-DL-R5d is the largest size.

Or do not load the image, how to set it?

**Comment by zzxhll** [comment]
It is useless to modify the parameters in config.ini with Qo-DL-R5d. Is the next version of config.ini custom modified?

**Comment by DashLt** [comment]
It's not useless, I don't even know why it isn't working. You're changing alcovs to "-1" to disable it?

**Comment by zzxhll** [comment]
Change alcovs to "-1" and download the prompt Qo-DL.py error. You will know when you try it.

**Comment by zzxhll** [comment]
coverSize = "-1" and an error occurred in the download.
![2](https://user-images.githubusercontent.com/53909508/62826744-88ea1500-bbf3-11e9-924e-f38a0452c1e0.jpg)

**Comment by khazz89** [comment]
> coverSize = "-1" and an error occurred in the download.
> ![2](https://user-images.githubusercontent.com/53909508/62826744-88ea1500-bbf3-11e9-924e-f38a0452c1e0.jpg)
0 = 50x50, 1 = 230x230, 2 = 600x600, 3 = max
-1 = no cover fetched

**Comment by KGB-USSR** [comment]
Same problem. Only option 3 works.
