### ISSUE TITLE
Restricted by right holders

### ISSUE THREAD

**Issue by L0nelyW0lf** [Sorrow446/Qo-DL#102]
Why i am still getting Restricted by Right holders error.

**Comment by KGB-USSR** [comment]
Same problem on all releases and on different proxies.

**Comment by khazz89** [comment]
Not every album/song are available for downloading, if they are marked with light grey that means can't be downloaded coz they are restricted by right holders.
Just to be sure could you share the link of the album?

**Comment by Sorrow446** [comment]
> Same problem on all releases and on different proxies.

Proxy support has been broken since switching to PySmartDL.

**Comment by DashLt** [comment]
Please remove appId and appSecret in your config file and let Qo-DL get you a new one.

**Comment by KGB-USSR** [comment]
> Please remove appId and appSecret in your config file and let Qo-DL get you a new one.

Thank you, it works.
