### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by botezat** [Sorrow446/Qo-DL#104]
Hello **Sorrow446** & **DashLt** :)
Please increase download speed by 100%
![1](https://user-images.githubusercontent.com/50467655/63215871-888ed400-c135-11e9-9ab1-3b7a0ef9f9b5.jpg)
Thanks :)

**Comment by DashLt** [comment]
what in ever living fuck

**Comment by botezat** [comment]
????????

**Comment by DashLt** [comment]
We can't just increase your download speed. That's not how the internet or computers work.

**Comment by botezat** [comment]
speed in highresaudio
![2](https://user-images.githubusercontent.com/50467655/63216222-deb24600-c13a-11e9-97a9-922ff278eb40.jpg)

speed in qobuz
![1](https://user-images.githubusercontent.com/50467655/63216226-eb369e80-c13a-11e9-9de3-fed47e123cf7.jpg)

**Comment by DashLt** [comment]
highresaudio uses different servers than Qobuz.

**Comment by botezat** [comment]
sorry :(
