### ISSUE TITLE
https://thoas.feralhosting.com/sorrow/Qobuz-DL/App.txt link is broken, and the app doesn't get the real id and secret id alone.

### ISSUE THREAD

**Issue by darkangel2325** [Sorrow446/Qo-DL#119]
Since 10 or more days the link disappeared, it was the only way to make the program work, but now that's no longer accessible there's no way to make the app work, can someone put the content of the link back online? or can he just share his working id and secret id? Even old versions of qobuz-dl are inaccessible.

**Comment by bascurtiz** [comment]
http://web.archive.org/web/20190728235035/https://thoas.feralhosting.com/sorrow/Qobuz-DL/App.txt

**Comment by darkangel2325** [comment]
> http://web.archive.org/web/20190728235035/https://thoas.feralhosting.com/sorrow/Qobuz-DL/App.txt

Thank you so much!

**Comment by darkangel2325** [comment]
As of now, no ids and secret ids are working, the app says they aren't right and cleans it by putting in another that's truly not working. Seems like it's the end for this app.
