### ISSUE TITLE
I get certificate errors in Linux

### ISSUE THREAD

**Issue by shillshocked** [Sorrow446/Qo-DL#12]
Linux error:

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>
[4181] Failed to execute script Qobuz-DL_Lin
`

**Comment by Sorrow446** [comment]
The code to fix this is already implemented in the latest version (Qo-DL: 9th Mar 19 - Release 4e). Tested working on Mint + Ubuntu. I'll look into this.

**Comment by shillshocked** [comment]
I downloaded the most recent version available on github and installed it on Arch, in case you're curious.

**Comment by Sorrow446** [comment]
Please try R5.

**Comment by shillshocked** [comment]
Fixed the certificate problem. But still can't download due to restrictions. Using UK VPN.
