### ISSUE TITLE
Still can't download.

### ISSUE THREAD

**Issue by ZPH666666** [Sorrow446/Qo-DL#122]
I received the update today, but it still hasn't worked. What should I do

**Comment by Superhackman** [comment]
@ZPH666666 
This is strange thanks dash this is working again, I do not know what is doing wrong but it works for me for now
it would be interesting where to get the appsecret since the app_id can be easily obtained
![image](https://user-images.githubusercontent.com/27593140/66252349-3bd07e00-e720-11e9-84fd-efb86901097a.png)

**Comment by Superhackman** [comment]
@ZPH666666 I simply install python 3.7 and start cmd as admin and run pip install --upgrade pip and then pip install -r requirements.txt inside the Qo-DL cd "path" folder and then edit config.ini by entering email and password and then run Qo-DL.py and automatically got the app_id and appsecret and then I ask for a URL

**Comment by darkangel2325** [comment]
Same problem here... tracks are still restricted, and i did everything you did there.. don't know what else to do.

**Comment by Superhackman** [comment]
@darkangel2325 
How strange, it works perfect for me, try using proxy

**Comment by Superhackman** [comment]
![image](https://user-images.githubusercontent.com/27593140/66252854-21999e80-e726-11e9-9dbf-f4bcadce81e3.png)
![image](https://user-images.githubusercontent.com/27593140/66252865-2eb68d80-e726-11e9-8450-85dd6f8b3f74.png)

**Comment by Superhackman** [comment]
what worries me is that it will happen if qobuz gets to know that there are these types of downloaders, as there are companies and even qobuz reviews the repositories of the developers

**Comment by ZPH666666** [comment]
@Superhackman Can you compress the whole software and send it to me? Delete emails and passwords

**Comment by Superhackman** [comment]
@facebook?

**Comment by Superhackman** [comment]
@ZPH666666 is that I send it publicly like here on github everyone will start downloading it since I am going to share my account because it is a 30-day trial and I just want you to try it if it works for you with that account

**Comment by ZPH666666** [comment]
Facebook is ok

**Comment by Superhackman** [comment]
@ZPH666666 email?

**Comment by ZPH666666** [comment]
18005881511@163.com

**Comment by ZPH666666** [comment]
I'm sorry I'm a Chinese and didn't sign up for facebook

**Comment by Superhackman** [comment]
Ok, it's too late, I got it before you sent it to me

**Comment by ZPH666666** [comment]
I'm sorry I caused you trouble

**Comment by ZPH666666** [comment]
or zppppph@gmail.com

**Comment by Superhackman** [comment]
I have your email before you wrote it here

**Comment by Superhackman** [comment]
18005881511@163.com

**Comment by Superhackman** [comment]
https://api.github.com/users/ZPH666666/events/public

**Comment by ZPH666666** [comment]
oh

**Comment by Superhackman** [comment]
in a line of code I looked for email and it came out

**Comment by ZPH666666** [comment]
So you sent it to me in the mail?

**Comment by Superhackman** [comment]
gmail

**Comment by ZPH666666** [comment]
ok

**Comment by ZPH666666** [comment]
thanks

**Comment by Superhackman** [comment]
send

**Comment by ZPH666666** [comment]
thanks a lot

**Comment by ZPH666666** [comment]
thanks,but it still not working

**Comment by Superhackman** [comment]
what error do you get
please capture

**Comment by Superhackman** [comment]
I remind you that this type of service like qobuz is blocked in your country in china

**Comment by ZPH666666** [comment]
![捕获](https://user-images.githubusercontent.com/53807952/66253507-ef2a8880-e79b-11e9-9d2c-5fca2b4daa24.PNG)

**Comment by ZPH666666** [comment]
United States to no avail




| |
18005881511
|
|
邮箱：18005881511@163.com
|

Signature is customized by Netease Mail Master

On 10/05/2019 18:14, Fabriccio Antonio Guzman Denham Deliot wrote:

I remind you that this type of service like qobuz is blocked in your country in china

**Comment by Superhackman** [comment]
I do not understand what you mean?

**Comment by ZPH666666** [comment]
Using an American VPN doesn't help either

**Comment by Superhackman** [comment]
that music you want to download can be played from the qobuz website?

**Comment by ZPH666666** [comment]
yes

**Comment by Superhackman** [comment]
Do you access qobuz with VPN or without VPN?

**Comment by kovkalin** [comment]
can you send me one also?

**Comment by ZPH666666** [comment]
with VPN

**Comment by clash108** [comment]
bro you can do a video tutorial how to run this in every step?

**Comment by Superhackman** [comment]
@ZPH666666 the vpn should be the problem, try using proxy, probably qobuz is blocking all the vpn

**Comment by Superhackman** [comment]
configure a proxy in the config.ini file

**Comment by clash108** [comment]
@Superhackman  bro you can do a video tutorial how to run this in every step?

**Comment by ZPH666666** [comment]
What proxy do I need

**Comment by ZPH666666** [comment]
Sorry. I just went to eat.

**Comment by edman84** [comment]
![2019-10-05_130244](https://user-images.githubusercontent.com/35334479/66254009-94c80280-e770-11e9-979f-273d9ee6aac3.jpg)

please help

**Comment by nihalsharma** [comment]
> @ZPH666666 the vpn should be the problem, try using proxy, probably qobuz is blocking all the vpn

What proxy settings to use?

**Comment by PUREBKK** [comment]
![2019-10-05_191503](https://user-images.githubusercontent.com/56193909/66254721-87c50680-e7a4-11e9-86a5-bd5f1b0999c3.jpg)

please help

**Comment by shinkibo** [comment]
Same problem for me. but I founda solution that will maybe help other.
Each time I try to download using Qo-DL_Win_x86.exe, it didn't work.
Each time I use a command line to run Qo-DL.py, it worked.

**Comment by edman84** [comment]
> Same problem for me. but I founda solution that will maybe help other.
> Each time I try to download using Qo-DL_Win_x86.exe, it didn't work.
> Each time I use a command line to run Qo-DL.py, it worked.

can you explain how to use Qo-DL.py?

**Comment by relax1980** [comment]
"Each time I use a command line to run Qo-DL.py, it worked"

if you can explain us would be very helpful :-)

**Comment by shinkibo** [comment]
by using a command prompt.
1. open command prompt
2. change directory to the one where Qo-DL.py is
3. run Qo-DL.py just with "Qo-DL.py" (without the quote)

**Comment by relax1980** [comment]
C:\Windows\system32>C:\Users\Rondo\Desktop\Qo-DL-master\Qo-DL.py
Traceback (most recent call last):
  File "C:\Users\Rondo\Desktop\Qo-DL-master\Qo-DL.py", line 29, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Superhackman** [comment]
@relax1980 
817/5000
installation instructions
1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
2. Unzip the zip with winrar or 7zip
3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
4. start cmd as administrator
5. write in cmd pip install --upgrade pip and enter to update pip
6. write in cmd cd plus the path of the file Qo-DL.py
ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
7. write in cmd pip install -r requirements.txt and enter and wait
8. edit and write your email and password in the config.ini file
9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download

**Comment by Superhackman** [comment]
Try using this VPN for those who have copyright issues https://download.vpngate.jp/common/cd.aspx/vpngate-client-2019.10.06-build-9696.145399.zip
because I just tried it if you download it well using this vpn

**Comment by nihalsharma** [comment]
> Try using this VPN for those who have copyright issues https://download.vpngate.jp/common/cd.aspx/vpngate-client-2019.10.06-build-9696.145399.zip
> because I just tried it if you download it well using this vpn

I do not think its working even with a VPN. Please help with a solution otherwise stop having fun. Thanks

**Comment by kovkalin** [comment]
> 

> Try using this VPN for those who have copyright issues https://download.vpngate.jp/common/cd.aspx/vpngate-client-2019.10.06-build-9696.145399.zip
> because I just tried it if you download it well using this vpn



> @relax1980
> 817/5000
> installation instructions
> 
> 1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
> 2. Unzip the zip with winrar or 7zip
> 3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
> 4. start cmd as administrator
> 5. write in cmd pip install --upgrade pip and enter to update pip
> 6. write in cmd cd plus the path of the file Qo-DL.py
>    ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
> 7. write in cmd pip install -r requirements.txt and enter and wait
> 8. edit and write your email and password in the config.ini file
> 9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download

@super hack

step 5,6,7 are very difficult to finish and can you provide a more detailed guide, etc how to upgrade the pip install. thanks so much.

**Comment by Superhackman** [comment]
for those who do not work the vpn, try using proxy
1. Go to this website http://spys.one/free-proxy-list/ and choose whatever HTTPS but I recommend using one where the location is available qobuz
ex: United States
2. open config.ini and edit it by typing the ip proxy + the port between the quotes ""
ex. proxy = "173.46.67.172:58517"
Try this to see if it works for you and if it doesn't work, I can't help you anymore, I'm sorry

**Comment by Superhackman** [comment]
https://datatofish.com/upgrade-pip/

**Comment by Refelinux** [comment]
Can i ask you, where you from? How did you download the track that even do not exist (i have typed the link from your screenshot)

**Comment by firebfm** [comment]
Working for me. If it's not working for you then you are not using the .py version or your app id/secret is wrong. Save this as .py https://raw.githubusercontent.com/Sorrow446/Qo-DL/master/Qo-DL.py. Open it in IDLE (comes installed with python) and run it.

**Comment by Koatohee** [comment]
> @ZPH666666 I simply install python 3.7 and start cmd as admin and run pip install --upgrade pip and then pip install -r requirements.txt inside the Qo-DL cd "path" folder and then edit config.ini by entering email and password and then run Qo-DL.py and automatically got the app_id and appsecret and then I ask for a URL
> 
> Make sure you have a Premium or Hi-Fi account

your tip helped. thank you.

**Comment by kovkalin** [comment]
> https://datatofish.com/upgrade-pip/

i don't know what to write under the path "qo-dl-master" for install -r requirements.txt .And can you help me again?

**Comment by nihalsharma** [comment]
> Can i ask you, where you from Superhackman? How did you download the track that even do not exist (i have typed the link from your screenshot and i have nothing except main page of qobuz)

I know, they are just having fun. It was not working for the user who opened this issue, now he has also joined the party.

**Comment by VadKul** [comment]
Superhackman.
Thank you for help.

**Comment by mimirak** [comment]
> 
> 
> @relax1980
> installation instructions
> 
>     1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
> 
>     2. Unzip the zip with winrar or 7zip
> 
>     3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
> 
>     4. start cmd as administrator
> 
>     5. write in cmd pip install --upgrade pip and enter to update pip
> 
>     6. write in cmd cd plus the path of the file Qo-DL.py
>        ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
> 
>     7. write in cmd pip install -r requirements.txt and enter and wait
> 
>     8. edit and write your email and password in the config.ini file
> 
>     9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download

Thank you Superhackman. I understand every step, except step 7. How do we install -r requirements.txt ? What is the exact syntax?
That is what I get:
E:\Qo-DL-master>cmd pip install -r requirements.txt
Microsoft Windows [version 10.0.17763.775]
(c) 2018 Microsoft Corporation. Tous droits réservés.

Any help would be great!

**Comment by khazz89** [comment]
> @relax1980
> installation instructions
> 
> 1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
> 2. Unzip the zip with winrar or 7zip
> 3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
> 4. start cmd as administrator
> 5. write in cmd pip install --upgrade pip and enter to update pip
> 6. write in cmd cd plus the path of the file Qo-DL.py
>    ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
> 7. write in cmd pip install -r requirements.txt and enter and wait
> 8. edit and write your email and password in the config.ini file
> 9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download

Oh sht this actually worked, thx brow 
![image](https://user-images.githubusercontent.com/53316165/66274795-be079200-e847-11e9-80d4-b0bdb35c4d92.png)

**Comment by TheSunKingXIV** [comment]
> > @relax1980
> > installation instructions
> > 
> > 1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
> > 2. Unzip the zip with winrar or 7zip
> > 3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
> > 4. start cmd as administrator
> > 5. write in cmd pip install --upgrade pip and enter to update pip
> > 6. write in cmd cd plus the path of the file Qo-DL.py
> >    ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
> > 7. write in cmd pip install -r requirements.txt and enter and wait
> > 8. edit and write your email and password in the config.ini file
> > 9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download
> 
> Oh sht this actually worked, thx brow
> ![image](https://user-images.githubusercontent.com/53316165/66274795-be079200-e847-11e9-80d4-b0bdb35c4d92.png)

Dude can you share with me the complete software pleeease? I'll thank you solo much!

**Comment by khazz89** [comment]
> > > @relax1980
> > > installation instructions
> > > 
> > > 1. Download the repository from github https://github.com/Sorrow446/Qo-DL/archive/master.zip
> > > 2. Unzip the zip with winrar or 7zip
> > > 3. Download Python 3.7.4 and install by checking path https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
> > > 4. start cmd as administrator
> > > 5. write in cmd pip install --upgrade pip and enter to update pip
> > > 6. write in cmd cd plus the path of the file Qo-DL.py
> > >    ex: cd C: \ Users \ fabri \ Downloads \ Qo-DL-master \ Qo-DL-master
> > > 7. write in cmd pip install -r requirements.txt and enter and wait
> > > 8. edit and write your email and password in the config.ini file
> > > 9. Run Qo-DL.py by typing in cmd python Qo-DL.py or simply Qo-DL.py only and wait for it to generate your app_id and app_secret until you are asked to paste a url to download
> > 
> > 
> > Oh sht this actually worked, thx brow
> > ![image](https://user-images.githubusercontent.com/53316165/66274795-be079200-e847-11e9-80d4-b0bdb35c4d92.png)
> 
> Dude can you share with me the complete software pleeease? I'll thank you solo much!

I just followed the instructions but with a CLEAN install, btw i have hi fi + sublime paid account, idk if it is a positive thing to mention and i'm using a VPN as somebody suggested.

**Comment by firebfm** [comment]
Account is associated with the country's ip address at the time of creation. I signed up with UK ip address and now I never need vpn to download.

**Comment by khazz89** [comment]
> Account is associated with the country's ip address at the time of creation. I signed up with UK ip address and now I never need vpn to download.

That's bcz u r living in the uk, but my account is from germany and i need a VPN for germany, just saying.

**Comment by ZPH666666** [comment]
@Superhackman Thank you bro,it works

**Comment by fickpyanka** [comment]
C:\WINDOWS\system32>pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
Could not install packages due to an EnvironmentError: [WinError 5] Отказано в доступе: 'c:\\users\\fickoyanka\\appdata\\local\\programs\\python\\python37-32\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.  

What wrong? help

**Comment by Superhackman** [comment]
> C:\WINDOWS\system32>pip install --upgrade pip
> Collecting pip
> Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
> Installing collected packages: pip
> Found existing installation: pip 19.0.3
> Uninstalling pip-19.0.3:
> Could not install packages due to an EnvironmentError: [WinError 5] Отказано в доступе: 'c:\users\fickoyanka\appdata\local\programs\python\python37-32\scripts\pip.exe'
> Consider using the `--user` option or check the permissions.
> 
> What wrong? help

run cmd (command prompt) as administrator

**Comment by fickpyanka** [comment]
thanx for help? it's work!!

пн, 7 окт. 2019 г. в 20:41, Fabriccio Antonio Guzman Denham Deliot <
notifications@github.com>:

**Comment by DashLt** [comment]
> 
> 
> @Superhackman Thank you bro,it works
