### ISSUE TITLE
Arm/aarch64 version

### ISSUE THREAD

**Issue by SPAstef** [Sorrow446/Qo-DL#13]
Please could you cross-compile it for ARM and aarch64 so it can work on Android too?

**Comment by Sorrow446** [comment]
Hello. I'm not very experienced with Linux, but I'll give it a go. I don't have a rooted Android device, so I won't be able to do any testing. How would I go about doing this?

**Comment by SPAstef** [comment]
I don't think you need root. You just have to install termux (that can be used with root, but isn't mandatory). You can use a cross-compiler on your PC, depending on the operating system you're using, there should be some guides online, or you can compile it inside Termux. I tried to emulate an x86 environment in my Android, but it takes too much resources and is very inconvenient. Otherwise you can just publish the python code (there is  a tidal downloader written in  python, so you don't need to bother compiling).

**Comment by SPAstef** [comment]
Ok, try to follow these steps. I don't have the source code so I cannot tell you if it will compile or not, if you can't you can send me the source code and I'll try to compile it for you.
1) install Termux from Play Store
2) from Termux, install python with "pkg install python"
3) update everythin using "python -m pip install --upgrade pip setuptools wheel"
4) from Termux, install zlib-dev package with "pkg install zlib-dev"
5) install pyinstaller with "pip install pyinstaller"
6) run pyinstaller on your source code, with option --onefile to output only one executable file. Look in the pyinstaller website for more info.

**Comment by SPAstef** [comment]
Additional steps:
If "pyinstaller --onefile example.py" fails, you might have to install python-dev (with pkg install python-dev) and run "export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib" before compiling again

**Comment by Sorrow446** [comment]
I'd prefer to compile on my actual phone. Thank you for the steps. I'm familiar with pyinstaller. I'll do this later on today and let you know how I get on.

**Comment by Sorrow446** [comment]
Tried 3 different emulators. Only one worked, but failed to run on my phone (aarch64). Complaining about the binary, so the emu isn't using aarch64. Where can I go from here?

**Comment by SPAstef** [comment]
Did you install all dependencies? Can you post a screenshot of the errors?

**Comment by Sorrow446** [comment]
Yes. 100%. I'm about to sleep, but when I wake up next I'll look more into the issue. 
[This was the error.](https://github.com/pyinstaller/pyinstaller/issues/3903)

**Comment by SPAstef** [comment]
BTW I'm using a OnePlus 3 with Android 9 on it (rooted), but root doesn't seem to be required

**Comment by SPAstef** [comment]
I think you don't have a compiler installed... Try using pkg install gcc

**Comment by Sorrow446** [comment]
Finally! https://thoas.feralhosting.com/sorrow/Qobuz-DL/SS.png

**Comment by Sorrow446** [comment]
Do you, by any chance, know how to tell PyInstaller to compile for just ARM and not ARM64 on my ARM64 device? 

64:
https://thoas.feralhosting.com/sorrow/Qobuz-DL/Qo-DL_ARM64

**Comment by SPAstef** [comment]
Glad you found a workaround :).
About your 32-bit question: there are 2 possibilities:
1) (easy) follow the same steps on a 32-bit ARM device
2) (probably not-so-easy) you need to install the 32-bit version of python. Now, to do that it's PROBABLY better if you delete the current python installation, switch your repositories to 32-bit ones, and install the 32bit python... But you'll have to do some search (pyinstaller uses your installed python libraries to build, so if you have python64 it will only build for 64bit)

**Comment by SPAstef** [comment]
BTW I get this errors:
$ ./Qo-DL_ARM64
[28216] Error -3 from inflate: incorrect header check
[28216] Error decompressing _bisect.cpython-37m.so
Failed to write all bytes for _bisect.cpython-37m.so
fwrite: Bad address
$

**Comment by SPAstef** [comment]
And this is the file info of your binary:
./Qo-DL_ARM64: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, missing section headers

This is the info of a binary I built myself (and it works):
./tdl: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped

**Comment by Sorrow446** [comment]
Do you have a Discord or something where we could talk further?

**Comment by SPAstef** [comment]
Sure, discord is SPAstef#7223

**Comment by WellingtonMonteiro** [comment]
Não estou conseguindo baixar o pyinstaller.

**Comment by WellingtonMonteiro** [comment]
Alguém poderia colocar a explicação como instalar mais detalhadas.

**Comment by SPAstef** [comment]
@WellingtonMonteiro Sorrow has found a way to build the executable for Android, but it is not published yet

**Comment by Sorrow446** [comment]
We're still both testing at the moment. We have an ARM64 build working for both of us. It needs a little bit more testing though.

**Comment by Sorrow446** [comment]
Builds up.

**Comment by WellingtonMonteiro** [comment]
Vai desenvolver o projeto mas não
?
