### ISSUE TITLE
aborts playlist download before ending first track

### ISSUE THREAD

**Issue by Anis108** [Sorrow446/Qo-DL#14]
Im using a windows 10 - 64 installation
Entered the details. (email, App_id & App-secret, Password hashed, User_auth_token)
No Proxy & No VPN

My subscription is shown corretly.
It starts playlist download and then closes the window directly after reaching 100% download of the first track.

How to proceed to solve that?

**Comment by Sorrow446** [comment]
I'll look into this when I next decide to work on Qo Playlist. It needs quite a bit of work. It's the next thing in my to-do list. Please send the playlist URL.

**Comment by Anis108** [comment]
https://open.qobuz.com/album/3149028062823

**Comment by Sorrow446** [comment]
Fixed.
