### ISSUE TITLE
can't download...

### ISSUE THREAD

**Issue by chrispadi** [Sorrow446/Qo-DL#2]
it says,,,

The API didn't return a release year. 'xxxx' will be used instead for the tags.
Whitney Houston - I Wish You Love: More From The Bodyguard

Track 1 is restricted by right holders. Can't download.
Track 2 is restricted by right holders. Can't download.
Track 3 is restricted by right holders. Can't download.
Track 4 is restricted by right holders. Can't download.
Track 5 is restricted by right holders. Can't download.
Track 6 is restricted by right holders. Can't download.
Track 7 is restricted by right holders. Can't download.
Track 8 is restricted by right holders. Can't download.
Track 9 is restricted by right holders. Can't download.
Track 10 is restricted by right holders. Can't download.
Track 11 is restricted by right holders. Can't download.
Track 12 is restricted by right holders. Can't download.
Track 13 is restricted by right holders. Can't download.
Track 14 is restricted by right holders. Can't download.

![qo_dl](https://user-images.githubusercontent.com/33798560/54067823-e8787900-427f-11e9-8ccb-5f942f0accf5.JPG)

**Comment by Sorrow446** [comment]
From the troubleshooting section. Does this happen just with this album?
> If you're getting this for every album you're trying to download, you either need a new uat or the app id + sec are dead. To get a new uat, wipe your current uat from the config file and start up Qo-DL. It'll give you a new one. Input this into your config file. If you're getting this for specific albums, there's either a region lock or the track is actually restricted by the right holders.

**Comment by chrispadi** [comment]
yes, all the same if i tried some other artist, it's denied, ell try to chage some id + sec might work

**Comment by Sorrow446** [comment]
Okay now?

**Comment by chrispadi** [comment]
still going to check on that, cleaning my laptop from malware,maybe they're the one that causes, i'll inform you later if i can go through, thanks

chris    On Wednesday, March 13, 2019, 12:20:51 PM GMT+8, Sorrow446 <notifications@github.com> wrote:  
 
 
Okay now?

**Comment by shammu4real** [comment]
Still not yet resolved...

![Untitled](https://user-images.githubusercontent.com/40962336/54333399-56d68600-4648-11e9-9b0e-aa4df7b95f8c.jpg)

Please help

**Comment by Sorrow446** [comment]
> Still not yet resolved...
> 
> ![Untitled](https://user-images.githubusercontent.com/40962336/54333399-56d68600-4648-11e9-9b0e-aa4df7b95f8c.jpg)
> 
> Please help

Which app id / secret combo are you using? If you're using the top combo, this is a region lock.

**Comment by shammu4real** [comment]
> > Still not yet resolved...
> > ![Untitled](https://user-images.githubusercontent.com/40962336/54333399-56d68600-4648-11e9-9b0e-aa4df7b95f8c.jpg)
> > Please help
> 
> Which app id / secret combo are you using? If you're using the top combo, this is a region lock.

Using 421125438 :  1e51aa18d871fc2b5a00ca9d9d3f1f55

**Comment by Sorrow446** [comment]
> > > Still not yet resolved...
> > > ![Untitled](https://user-images.githubusercontent.com/40962336/54333399-56d68600-4648-11e9-9b0e-aa4df7b95f8c.jpg)
> > > Please help
> > 
> > 
> > Which app id / secret combo are you using? If you're using the top combo, this is a region lock.
> 
> Using 421125438 : 1e51aa18d871fc2b5a00ca9d9d3f1f55

Working combo. It's a region lock then. Account region is locked to the place of registration.

**Comment by shammu4real** [comment]
Which region is accepted to use this app? thx

**Comment by An0nima** [comment]
@chrispadi @shammu4real
Please, you can download this album in mp3 and flac format for me?, I will be eternally grateful, I am only interested in this album.

`https://www.qobuz.com/gb-en/album/controlalo-desde-lejos-david-moleon/jkq324obxdkrb`

**Comment by Sorrow446** [comment]
> Which region is accepted to use this app? thx

Any region account will work with Qo-DL. The best region account to have is a French one.

**Comment by chrispadi** [comment]
still the same, can't download, says it's lock

**Comment by shammu4real** [comment]
The account i have is registered in france but still not working....

**Comment by Sorrow446** [comment]
Downloads fine for me with a French account + UK VPN.

**Comment by shammu4real** [comment]
Which VPN you use? Can you suggest? I do have a French Account but unable to download...

TIA.

**Comment by shillshocked** [comment]
VPNs don't work for me. I have another downloader, too, it works better, but it only gets 30 seconds previews.

**Comment by Hemps38** [comment]
> VPNs don't work for me. I have another downloader, too, it works better, but it only gets 30 second previews.

What other downlaoder are you using, qobuz-get?

**Comment by Slypser** [comment]
How do I fix the error "not found 404, bad url or a proxy / vpn is need"

**Comment by Slypser** [comment]
> > > > Still not yet resolved...
> > > > ![Untitled](https://user-images.githubusercontent.com/40962336/54333399-56d68600-4648-11e9-9b0e-aa4df7b95f8c.jpg)
> > > > Please help
> > > 
> > > 
> > > Which app id / secret combo are you using? If you're using the top combo, this is a region lock.
> > 
> > 
> > Using 421125438 : 1e51aa18d871fc2b5a00ca9d9d3f1f55
> 
> Working combo. It's a region lock then. Account region is locked to the place of registration.

the same thing happens to me, I can not download, I have a French account and I use vpn from france in the united kingdom and I do not download it either.

**Comment by aphelion1** [comment]
app doesn't work anymore fix that please

**Comment by botezat** [comment]
Hello:) Thank you very much Sorrow446 :)
Problem downloads:
https://play.qobuz.com/album/ci1j1xnv8x9za

**Comment by botezat** [comment]
Sorry.... And proxy for new version not working :(

**Comment by Sorrow446** [comment]
I didn't touch the proxy code. What's the error?

Needs to be formatted like: <IP address>:<port>

**Comment by shinkibo** [comment]
Hello
Just in case, I had the same problem and found an easy solution.
When I tried to download, Qobuz player was already opened in chrome (to get the url).
I just close the player and It worked.
If the web player is opened I can't download but I can if it's closed.

**Comment by shillshocked** [comment]
I've never been able to download with this (either windows or linux)

**Comment by Sorrow446** [comment]
> Hello
> Just in case, I had the same problem and found an easy solution.
> When I tried to download, Qobuz player was already opened in chrome (to get the url).
> I just close the player and It worked.
> If the web player is opened I can't download but I can if it's closed.

I see. Thank you for the info :).

**Comment by shammu4real** [comment]
> Hello
> Just in case, I had the same problem and found an easy solution.
> When I tried to download, Qobuz player was already opened in chrome (to get the url).
> I just close the player and It worked.
> If the web player is opened I can't download but I can if it's closed.

Not working for me :-(
