### ISSUE TITLE
Check to see if config file is present.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/Qo-DL#20]
This should have been implemented a long time ago.

**Comment by Sorrow446** [comment]
Written. Will be in next build.

**Comment by WellingtonMonteiro** [comment]
Não estou conseguindo baixar no telefone. A arquitetura do meu celular é AMRv7.
Você poderia me ajudar?

**Comment by Sorrow446** [comment]
You need to use Qo-DL_ARM32 for ARMv7. There are instructions on the main page.

**Comment by WellingtonMonteiro** [comment]
Está dando este erro.
chmod +x Qo-DL_ARM32
$ ./Qo-DL_ARM32
CANNOT LINK EXECUTABLE "./Qo-DL_ARM32": library "libz.so.1" not found
Aborted 
Como faço para resolver?

**Comment by WellingtonMonteiro** [comment]
Eu consegui instalar libz mas continua com mesmo erro me ajude por favor.

**Comment by SPAstef** [comment]
You need to install libz-dev, the dll isn't included in the standard install

**Comment by Sorrow446** [comment]
Done.
