### ISSUE TITLE
can't download hi-res 

### ISSUE THREAD

**Issue by jimsaye** [Sorrow446/Qo-DL#22]
i can't download hi-res only 16-bit / 44.1  kHz FLAC max 
i used Qo-DL_x64_Lin the last version
i'm login with  Qobuz Studio account
thank's

**Comment by Sorrow446** [comment]
Is this happening for every single album?

**Comment by jimsaye** [comment]
yes all the downloads

**Comment by jimsaye** [comment]
it' my uat i change it and it's ok for download hi-res
