### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Koatohee** [Sorrow446/Qo-DL#23]
Can't download simply anything. Program worked fine before. I'm using latest working version. I have Qobuz studio account. I've never had this issue before until a recent time. 
![Annotation 2019-05-16 025057](https://user-images.githubusercontent.com/50683360/57816952-1cfe2a80-7732-11e9-9aef-ddeffc78adf0.png)
Any possible fix?
GUI:
![Annotation 2019-05-16 025719](https://user-images.githubusercontent.com/50683360/57817085-ad3c6f80-7732-11e9-838f-a351b3310dbc.png)
![Annotation 2019-05-16 025641](https://user-images.githubusercontent.com/50683360/57817086-ad3c6f80-7732-11e9-9a8b-72408fa051e3.png)

**Comment by Sorrow446** [comment]
It could be that the app id / secret combo you're using has stopped working. I'll test them all later on today.

**Comment by Koatohee** [comment]
> It could be that the app id / secret combo you're using has stopped working. I'll test them all later on today.

Hoping for a fix. I've been told it may be the region lock but I have my account registered as France.

**Comment by Koatohee** [comment]
UK vpn helped with region lock. Works good now.

**Comment by jimsaye** [comment]
Koatohee tu récupère les fichiers dans quelle qualité ? moi j'ai un abo Studio mais je ne récupère les fichiers seulement en qualité cd  avec Qo-DL.

**Comment by Koatohee** [comment]
> Koatohee tu récupère les fichiers dans quelle qualité ? moi j'ai un abo Studio mais je ne récupère les fichiers seulement en qualité cd avec Qo-DL.

J'ai un compte studio. essayez de changer certains paramètres dans config.ini

**Comment by jimsaye** [comment]
j'ai déja essayé format_id = "7" et format_id = "27" mais uniquement des téléchargements en 16-bit / 44.1 kHz au maximum.
tu utilises un vpn ?

**Comment by jimsaye** [comment]
c'etait mon UAT token tout est ok pour moi merci de ton aide

**Comment by Koatohee** [comment]
> c'etait mon UAT token tout est ok pour moi merci de ton aide

prendre plaisir
