### ISSUE TITLE
Qo-DL_ARM32

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Sorrow446/Qo-DL#24]
Está dando erro. 
chmod + x Qo-DL_ARM32 
$ ./Qo-DL_ARM32 
NÃO PODE LIGAR EXECUTAVEL "./Qo-DL_ARM32": biblioteca "libz.so.1" não encontrada 
Abortada

Como faço para resolver?

**Comment by Sorrow446** [comment]
The ARM32 build was compiled by [SPAstef](https://github.com/SPAstef). He's been away for a few days.
