### ISSUE TITLE
Complete track title not added to tags in flac files

### ISSUE THREAD

**Issue by janhjanh** [Sorrow446/Qo-DL#25]
When downloading flac, Qo-DL_x64 for Windows does not save the complete track name in the tag. Mp3 has not been tested as I only use flac.

Try this:
https://play.qobuz.com/album/q1opkcdz77t2b

All tracks are downloaded as "Believer" but without the version data. The correct name should as an example be "Believer (Joris Voorn Remix)" for track no. 2.

**Comment by Sorrow446** [comment]
This is how Qobuz's API returns the title data. I'll have it include the (x remix) etc. in the next build.

**Comment by panagiotis79** [comment]
Hello,when i try to download an album i get bad credetials,exciting,any help please?

**Comment by Sorrow446** [comment]
Added in r5a.
