### ISSUE TITLE
Bad credetials

### ISSUE THREAD

**Issue by panagiotis79** [Sorrow446/Qo-DL#26]
Hello,when i try to download one album i get the message bad credetials.exciting,any solution?

**Comment by Sorrow446** [comment]
> 401 - Unauthorized - Error that resulted from the user authentication.
This is a user fault. Check your creds.

**Comment by panagiotis79** [comment]
Sorry,you mean maybe i have make mistake in user_auth_token?

**Comment by Sorrow446** [comment]
It's either your email or pass.
