### ISSUE TITLE
Qo-DL_Win_x86.exe

### ISSUE THREAD

**Issue by botezat** [Sorrow446/Qo-DL#29]
Hello Sorrow446 :)
Thank you for updates.

Qo-DL_Win_x86.exe not working...

Invalid URL.....

**Comment by Sorrow446** [comment]
Welcome :).
What are you typing in?

**Comment by botezat** [comment]
![test](https://user-images.githubusercontent.com/50467655/58436098-576dad00-80cc-11e9-9fd8-6b0c84e157cc.gif)

**Comment by Sorrow446** [comment]
The "be-fr" triggers this. Use Qobuz Player URLs instead for now.

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/Qo-DL/pull/31/commits/04e2a3fdafc114f47e3f38205720f6ab8a7cf83f

**Comment by botezat** [comment]
Error after download :( link: https://play.qobuz.com/album/iirkzhopncmia
![test](https://user-images.githubusercontent.com/50467655/58438463-b2f16800-80d7-11e9-8be5-17537d56dd3e.gif)

**Comment by Sorrow446** [comment]
Reply with the error in text. GIF is broken.

**Comment by botezat** [comment]
the program stops after loading the first track

**Comment by DashLt** [comment]
Please try this with the new version.
