### ISSUE TITLE
UserAuthToken retrieval failure

### ISSUE THREAD

**Issue by Zaphain** [Sorrow446/Qo-DL#39]
I'm getting this when I try to use Qo-DL

C:\Qo-DL>qo-dl_win_x86.exe
Signed in successfully - Qobuz Studio account.

UserAuthToken field in config file is empty. Fetching it...
Traceback (most recent call last):
  File "Qo-DL.py", line 901, in <module>
  File "Qo-DL.py", line 614, in init
    get_uat()
  File "Qo-DL.py", line 54, in get_uat
    "email": email,
NameError: name 'email' is not defined
[15704] Failed to execute script Qo-DL

**Comment by Sorrow446** [comment]
Broken due to refactoring, sorry. Use the previous release. Email doesn't get passed to the function like it should be doing.

**Comment by DashLt** [comment]
This has been fixed in the newest release. Until there is a compiled release, please follow [these instructions.](https://github.com/Sorrow446/Qo-DL/issues/45#issuecomment-509017646)
