### ISSUE TITLE
exit on fail

### ISSUE THREAD

**Issue by lef38** [Sorrow446/Qo-DL#4]
The tool works very well, but sometimes it encounters a track that it can't download, for some reason.
That causes the tool to exit, it won't finish downloading the remaining tracks of the album, although they are available (I could retrieve them "manually " later). It happens quite frequently, once every 3 or 4 albums, I guess you got the problem as well ?

Also I usually end up being able to download the faulty track by retrying with different quality settings. My default setting is 16bit flac, so  I retry with HiRes, it usually doesn't work but sometimes it does (even though the downloaded track is also in 16bit flac as HiRes not available for that album). If not I then retry with mp3 and it works almost everytime.

So do you think you can fix the error, and if not, have the tool continue downloading the rest of the album, and try downloading the failing tracks in different quality ?

**Comment by Sorrow446** [comment]
Never happens to me, sorry. Could you provide some of the error messages? The quality fallback is actually handled entirely by the API. If your chosen quality isn't available, the next best quality will be returned.

**Comment by lef38** [comment]
The black console window is killed immediately, I get no chance to read the error message. Is there a way ? (I'm using the GUI version)

> If your chosen quality isn't available, the next best quality will be returned.

The file is available at Qobuz actually. I know that because if I retry 5/10 mn later, it works. So this feature is of no help in my case. The error that I have is probably of another kind.

**Comment by lef38** [comment]
I managed to get this :

![image](https://user-images.githubusercontent.com/48394640/54088746-5e084600-4361-11e9-8d0d-7f132405c76e.png)

**Comment by Sorrow446** [comment]
I see. I plan to add some code to prevent it from terminating on errors. After you call it, you can add a "PAUSE" in your batch file. Not sure about the other two OS's.

I see your new post, looks like Qobuz's servers are having problems.

**Comment by lef38** [comment]
Thank you !
In my case, if you retry the request immediately, it shouldn't work : this is curious but the same track is producing the error 500 steadily during say 5 to 10 mn, then it's ok. 
Perhaps you need to flush some cache before retrying ?

**Comment by lef38** [comment]
Another easy fix : i'm using the GUI exe, and the cover is downloaded in the GUI exe folder, not in the album folder

**Comment by Sorrow446** [comment]
By default, the album cover is downloaded to Qo-DL's folder and then deleted after tagging. Use the -k arg from the command line or Keep_cover in the config file to have it rename it to "folder.jpg" and move it to its respective album folder.

**Comment by lef38** [comment]
I missed that setting. Spot on ! Thank you.
BTW this week I had no error 500. As you said, Qobuz's servers had problems on Sunday probably.

**Comment by Sorrow446** [comment]
I'm glad :). You're welcome. They didn't bother to post anything on Twitter.
