### ISSUE TITLE
Force closing

### ISSUE THREAD

**Issue by L0nelyW0lf** [Sorrow446/Qo-DL#42]
when u insert the url its force closing am i the only one getting this error?

**Comment by dekker24** [comment]
I'm getting the same thing too.

**Comment by shinkibo** [comment]
I had this problem too.
If you keep trying it sometimes ended to work.
Also, I recently had to change App ID.

**Comment by L0nelyW0lf** [comment]
which version you are using @shinkibo & what to do with this error Track 1 is restricted by right holders. Can't download.

**Comment by shinkibo** [comment]
Still with release 4 (e i think).
I had this "right older error" too.
You need to change the App ID and leave blank the user_auth_token (to get a new one).
It worked for me.
