### ISSUE TITLE
Don't know what userauthtoken is

### ISSUE THREAD

**Issue by lilstavo** [Sorrow446/Qo-DL#44]
I'm just a dumb person on the internet here and I am trying to put my account info on the config to hopefully make the downloader run but I need an example of "userauthtoken".

Edit: It runs but after I put in the url it just closes, what did I put wrong in the config?

**Comment by AlexCeron** [comment]
Setup
Mandatory
The following need to be inputted into the config file:

App id
App secret - App IDs & secrets hosted here.
Email address
Format id - download quality (5 = 320 kbps MP3, 6 = 16-bit FLAC, 7 = 24-bit / =< 96kHz FLAC, 27 = best avail - 24-bit / >96 kHz =< 192 kHz FLAC).
MD5 hashed password - as of release 5, you may input it in plain text instead.
UserAuthToken - you'll be given this automatically if it's not already inputted in. App id & app secret are required.
NamingScheme - file naming scheme (1 = "01. ", 2 = "01 -").
coverSize - cover size to request from API (0 = 50x50, 1 = 230x230, 2 = 600x600, 3 = max).
KeepCover' - leave folder.jpg in album dir, Y or N. Not usable with Qobuz-DL_Playlist.
UseProxy - enable or disable proxy. "Y" or "N".
skipPwHashCheck - skip check to see if password is a valid MD5 hash. "Y" or "N".
embedCover - write covers to tracks. "Y" or "N".
checkForUpdates - check for updates. "Y" or "N".
All tags under "[Tags]" except comment - "Y" or "N".
You can't download ANY tracks with a free account.

**Comment by lilstavo** [comment]
Don't know if I did this right but when the window closes it still leaves behind the cover art in the downloads folder 
![SharedScreenshot](https://user-images.githubusercontent.com/52061587/59945688-36735000-941d-11e9-91b1-29769ee883ec.jpg)

**Comment by AlexCeron** [comment]
Ok, i had that issue with the last versión, for me works fine with the R4e version, try that one.

**Comment by lilstavo** [comment]
Can you link me it?

**Comment by AlexCeron** [comment]
https://thoas.feralhosting.com/sorrow/Qobuz-DL/Old%20Builds/

**Comment by lilstavo** [comment]
Can't seem to find it, what's the exact file?

**Comment by DashLt** [comment]
Remove the userAuthToken from the config file (leaving two quotes with nothing in them), and instead put in your password.
