### ISSUE TITLE
it randomly crashes

### ISSUE THREAD

**Issue by RealFantasy** [Sorrow446/Qo-DL#45]
While downloading it often crashes and I have to re download the full album
Using Release 5 Windows x64 version

(Release 5a is not working at all)

Here's the log:
```Downloading track 18 of 51: You're Crazy - 24-bit / 192 kHz FLAC  100%
Traceback (most recent call last):
  File "Qo-DL.py", line 718, in <module>
  File "Qo-DL.py", line 645, in rip
  File "site-packages\requests\models.py", line 896, in json
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[8580] Failed to execute script Qo-DL

**Comment by DashLt** [comment]
Please retry using the new version (the .py file). Until there is a compiled version, please follow these steps to install:

- If you don't already have python: Install the latest stable Python 3 release from python.org. On Windows, make sure to select "Add to PATH" before or after installation.
- Open up a command prompt as adminstrator/terminal and type `pip install requests clint mutagen nested_lookup`. If that fails, try pip3.
- Run Qo-DL with python Qo-DL.py (if that fails, python3)

**Comment by TheSunKingXIV** [comment]
@DashLt 
Hey men, thanks for your support!
Something is happening to me on your 3 and 4 step. Can you be more specific describing the way it does the compilation. I'm not an expert but very fast learnig. I already try but when install Python in CMD gives me a huge error and I can't get through the steps you wrote. I appreciate your guide!

**Comment by Koatohee** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

> Please retry using the new version (the .py file). Until there is a compiled version, please follow these steps to install:
> 
> * If you don't already have python: Install the latest stable Python 3 release from python.org. On Windows, make sure to select "Add to PATH" before or after installation.
> * Download Qo-DL.py, config.ini, and requirements.txt. Put them in the same folder.
> * Open up a command prompt as adminstrator/terminal and type `pip install -r requirements.txt`. If that fails, try pip3.
> * Run Qo-DL with python Qo-DL.py (if that fails, python3)

'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DashLt** [comment]
@TheSunKingXIV Wait for the compiled version, it'll come after I slim down the number of modules used.
@Koatohee like I said, try using pip3 instead of pip. If that doesn't work, see above.

**Comment by darkangel2325** [comment]
> Please retry using the new version (the .py file). Until there is a compiled version, please follow these steps to install:
> 
> * If you don't already have python: Install the latest stable Python 3 release from python.org. On Windows, make sure to select "Add to PATH" before or after installation.
> * Download Qo-DL.py, config.ini, and requirements.txt. Put them in the same folder.
> * Open up a command prompt as adminstrator/terminal and type `pip install -r requirements.txt`. If that fails, try pip3.
> * Run Qo-DL with python Qo-DL.py (if that fails, python3)
Tried to do as you said, but it gives me an error saying it can't find requirements, what i am doing wrong? here it's a picture.
![Immagine](https://user-images.githubusercontent.com/51389134/60829135-8475ab00-a1b4-11e9-8e98-f8a52a9110ee.png)

**Comment by DashLt** [comment]
Run it in the same directory as Qo-DL.

**Comment by Koatohee** [comment]
You'd be surprised, but indeed there are noobs on github. I couldn't get it working. Not recognized command.

**Comment by DashLt** [comment]
New version has been compiled, and I believe this error has been fixed.
