### ISSUE TITLE
Does the music lose some quality while ripping from qobuz?

### ISSUE THREAD

**Issue by darkangel2325** [Sorrow446/Qo-DL#48]
I am asking because to my ears seems to be differences between the ripped music and the streaming one on qobuz, it's just me or is there some loss in quality? Does this program rip music as bit perfect copies?

**Comment by Sorrow446** [comment]
The only changes Qo-DL makes to the tracks are the filenames and tags. The audio streams are not touched.

**Comment by darkangel2325** [comment]
Thank you very much for answering. So every version of Qo-DL makes bit perfect copies or just the most recent? i am using the old Qo-DL_r5, the one with with Qo-DL_x64.exe included.

**Comment by Sorrow446** [comment]
Welcome. Yes, all versions.

**Comment by robin2510** [comment]
It appears that you need a Hi-Fi subscription if you want to get a lossless rip, if you have premium - you will get 320 mp3 file even if you set it to flac.
