### ISSUE TITLE
Can't download an album, strange error appears.

### ISSUE THREAD

**Issue by darkangel2325** [Sorrow446/Qo-DL#50]
I am trying to download some albums, but i am unable to because the same error appears in all of them, this just happens while i am downloading these albums so i don't know what may cause this, it's not copyrights problems so i am at loss of ideas on how to solve it, maybe i have to change something in my config.ini?
This is the error, it appears just with this album and some others.
![Immagine](https://user-images.githubusercontent.com/51389134/60811376-68134780-a18f-11e9-8871-159b744bf15c.png)
What can i do to solve this?

**Comment by DashLt** [comment]
Please test with the new build.

**Comment by darkangel2325** [comment]
If i could i would test it, but i can't make it work, i don't know what i can do to make the program work. I downloaded the file, python too, but this is what tells me when i try to start the program, i don't know how to solve this..
![Immagine](https://user-images.githubusercontent.com/51389134/61579115-2a081300-ab01-11e9-8051-f85a6a3e36de.png)

**Comment by DashLt** [comment]
It's a windows thing, sorry, didn't do enough research. Will likely be fixed in the next build. (For reference, Windows doesn't allow you to end a folder name with a period. I didn't experience this as I'm on Linux.)

**Comment by DashLt** [comment]
This is sorta closed in 1074de7. Default behavior is now to add the year after the album name, and you can always a different character if you'd like. Frankly, I don't see another clean way to fix this, as anything else would require butchering the song title.
