### ISSUE TITLE
Can't Find Any Artists or Albums

### ISSUE THREAD

**Issue by Josh1983** [Sorrow446/Qo-DL#51]
QU-DL has worked for me in the past, but now QO-DL can't find any artists or albums when I execute a search. This is on Windows, using the GUI. I've uninstalled and reinstalled. After deleted and re-downloading, I put the new App ID and Secret and my email and password in the config file, then ran the GUI app and located the exe. However, it never gave me a UAT or populated it into my config. Could that be the issue? Any step-by-step help would be appreciated. Thanks!

**Comment by Josh1983** [comment]
Is no one else having issues with the GUI not displaying any artists when searching? This is driving me nuts. I even clean installed Windows 10 and re-installed Qo-DL and nothing changed.

**Comment by Sorrow446** [comment]
Please try R5c. About the GUI, I'll pass that onto my GUI dev.

**Comment by Josh1983** [comment]
Is there a working ID/secret available for GUI?

**Comment by Sorrow446** [comment]
Yep. I'm talking about the app ID & secret that is in the GUI's code. The plan is to get the GUI to use these from the config file.

**Comment by hyblif** [comment]
I have the same problem.more information should be added

**Comment by Josh1983** [comment]
Cool. Thanks. I'll use command line for now instead.

**Comment by Sorrow446** [comment]
Fixed. Sorry about that. Grab it in the releases section.
