### ISSUE TITLE
New version 5b

### ISSUE THREAD

**Issue by botezat** [Sorrow446/Qo-DL#52]
Hello Sorrow446 :)
Version 5b not working.

**Comment by botezat** [comment]
![sshot-1](https://user-images.githubusercontent.com/50467655/60929755-58911d00-a2bb-11e9-8dd6-b2121ee49de5.jpg)

**Comment by KGB-USSR** [comment]
Same problem.

**Comment by jimsaye** [comment]
Same problem Ubuntu x64 python 3.6

**Comment by TitouanGendron** [comment]
I solved the problem using app-id : 793410592 and app-secret : 0e47db7842364064b7019225eb19f5d2 on Debian. I also modified in Qo-dl.py  the header of the request (line around 289 )
`opener.addheaders = [('range', 'bytes=0-'), ('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64…) Gecko/20100101 Firefox/60.0'), ('referer', album_url)]`

I also had issues with encoding, i had to modify the python3.7/http/client.py file, adding # coding: utf8 at the top and replacing all 'latin-1' of the file by 'utf-8'. THIS IS VERY DANGEROUS! don't do this at home! or keep a backup of the original file!

hope it will help!

**Comment by botezat** [comment]
TitouanGendron :)
Thank you very much!

**Comment by jimsaye** [comment]
thank's , it's ok with this

**Comment by KGB-USSR** [comment]
Does not work on Windows 7 x64.

**Comment by botezat** [comment]
Please tell me. 
How in the name of the folder to add the year of release?

**Comment by TitouanGendron** [comment]
botezat,
find  (around line 850)
`		try:
			year2 = datetime.datetime.fromtimestamp(year).strftime('%Y')
		except OSError:
			print("The API didn't return a release year. Tag will be left empty.") 
			year2 = ""
`
then cut it and paste just before the line 
`		dlDir1 = f"{dlDir1ar2} - {dlDir1a2}"`
then you can add {year2} in the dlDir1 string wherever you want to put the year in the folder's name
({dlDir1ar2} is the artist and {dlDir1a2} is the album name)

**Comment by botezat** [comment]
Thank you. Not working.
![sshot-2](https://user-images.githubusercontent.com/50467655/61132062-45509e00-a4c3-11e9-8d4b-ff62e8cc955f.jpg)

**Comment by TitouanGendron** [comment]
this is an indentation error. Indentation is very import with python, as there a no bracket to define the range of the for loops or if or while or try... Only the indentation defines which lines are taken by the try statement.
You can also verify that the line begins by tabs and not spaces...

**Comment by botezat** [comment]
You are a very good man. 
Thank You very much :)

**Comment by DashLt** [comment]
Sorry for not seeing this earlier; 5c will bring some refactoring and a new downloader that should be less buggy. @TitouanGendron can you please tell me what exactly you changed in the header line?

**Comment by TitouanGendron** [comment]
I just changed the header to match with my OS and architecture but I don't think it matters a lot. I just copy past the header sent by my version of Firefox. I can try to see if it actually changes some thing tomorow if you whant.

**Comment by botezat** [comment]
**TitouanGendron** Sory.
Please tell me.
How in the name of the folder to add the year of release? For new version 5c...

**Comment by DashLt** [comment]
This has been fixed in 5c.

**Comment by botezat** [comment]
Thank You very much :)

**Comment by botezat** [comment]
Please add date of release for name folder
![sshot-1](https://user-images.githubusercontent.com/50467655/61577910-c842ab80-aaf6-11e9-81c1-ed4099b0942b.jpg)
![sshot-2](https://user-images.githubusercontent.com/50467655/61577911-cb3d9c00-aaf6-11e9-8f81-38ca33763eb6.jpg)
