### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by TheSunKingXIV** [Sorrow446/Qo-DL#53]
Hi everyone!

Is there someone who had a compiled version in Windows 10 (x64) that can share it with me?

Thank you so much.

**Comment by Jester0fTortuga** [comment]
Also would love that

**Comment by DashLt** [comment]
I'm currently refactoring the code and implementing a new downloader. Once this is finished, I will compile the new version. Sorry for the inconvenience!

**Comment by DashLt** [comment]
New version compiled and released.
