### ISSUE TITLE
Add track version to metadata and configurable folder/file name

### ISSUE THREAD

**Issue by botezat** [Sorrow446/Qo-DL#54]
Hello Sorrow446 :)
Please ad track version (trackTr = f"{item.get('title')} ({version})")
and please ad release date to name folder.

Thank You Very Much :)

**Comment by DashLt** [comment]
Sorry, just pushed 5c; this is definitely a good idea for the next version though.

**Comment by Sorrow446** [comment]
Sorry, this accidentally got removed. Track version added to 5c.

**Comment by botezat** [comment]
Thank you :)
Sorry, please add date of release for folder name
if:
![sshot-1](https://user-images.githubusercontent.com/50467655/61578357-3fc80900-aafe-11e9-8550-934c4b1e3e2e.jpg)
else:
![sshot-2](https://user-images.githubusercontent.com/50467655/61578366-54a49c80-aafe-11e9-810c-5b03661ed6bf.jpg)
Thank you very much :)

**Comment by Sorrow446** [comment]
That will definitely be included as an option in the next build.

Note to self: if album title already has a set of regular brackets in it, use square brackets instead for year.

**Comment by botezat** [comment]
Thank you **Sorrow446**
You are the best :)

**Comment by botezat** [comment]
**DashLt** Thank you very much :) You are the best :)

**Comment by DashLt** [comment]
You're welcome :)

**Comment by botezat** [comment]
**DashLt** Sorry. Please add for tags the real names of the performers
for example
if:
![2](https://user-images.githubusercontent.com/50467655/61884324-b56c1480-af04-11e9-9fdd-8e72d6efae95.jpg)
else:
![1](https://user-images.githubusercontent.com/50467655/61884348-c157d680-af04-11e9-8a14-8c0836012191.jpg)

https://www.qobuz.com/be-fr/album/italian-rococo-at-the-hermitage-claire-genewein-la-cetra-consort/4260123642587
