### ISSUE TITLE
r5c bug

### ISSUE THREAD

**Issue by KGB-USSR** [Sorrow446/Qo-DL#58]
del

**Comment by KGB-USSR** [comment]
r5c not working, win 7 x64, python 3.7.1 x64, coverSize = "3

![2019-07-20_182614](https://user-images.githubusercontent.com/35596326/61578125-fbe3fc80-ab1b-11e9-9455-1abb4fd22bb1.jpg)
", useProxy = "y".

**Comment by KGB-USSR** [comment]
r5c not working, win 7 x64, python 3.7.1 x64, coverSize = "3", useProxy = "y", app-id #1

![2019-07-20_184823](https://user-images.githubusercontent.com/35596326/61578320-26838480-ab1f-11e9-8ba1-b04f58f9cb65.jpg)

**Comment by Sorrow446** [comment]
For every inputted URL or a specific one?

**Comment by DashLt** [comment]
> 
> 
> r5c not working, win 7 x64, python 3.7.1 x64, pySmartDL 1.3.1, coverSize = "2", useProxy = "y" -> **r4e is ok.**
> 
> ![2019-07-20_181524](https://user-images.githubusercontent.com/35596326/61578052-005be580-ab1b-11e9-959c-2a0df5c68a29.jpg)

Make sure alcovs doesn't have quotes around it in config.ini

+1 to Sorrow though, what URL if any specific one?

**Comment by KGB-USSR** [comment]
> For every inputted URL or a specific one?
For every.

New r5c also does not work:

![2019-07-21_214404](https://user-images.githubusercontent.com/35596326/61592720-41c6c080-ac01-11e9-811e-8cbf777244e1.jpg)

**Comment by DashLt** [comment]
Try using a VPN/proxy from another country, or if you're using store URLs, try using streaming ones. (play.qobuz.com/album/etc., in this case you'll have to search it up there.)
