### ISSUE TITLE
Where Could I find my own App_secret?/I know how to find my own App_id

### ISSUE THREAD

**Issue by sskinhg** [Sorrow446/Qo-DL#59]
Could I just use the implementations in the documentation(config.ini) or use my own instead.
Also, the console will automatically close even though I fill all the requirements info in the config.ini./System Version Win10 1903 x64.

**Comment by sskinhg** [comment]
I created my config.ini and fill the information but the application won't launch 
File "Qo-DL.py", line 704, in <module>
  File "Qo-DL.py", line 530, in init
AttributeError: 'NoneType' object has no attribute 'lower'
[7864] Failed to execute script Qo-DL

**Comment by Sorrow446** [comment]
How are you launching this? Is it the compiled build?

**Comment by sskinhg** [comment]
It works now, however, they're too many records there said restricted by the rights holder can't be download

**Comment by DashLt** [comment]
Please try redownloading 5c, Sorrow has updated a few things.

**Comment by DashLt** [comment]
Should be fixed in 560c03f.
