### ISSUE TITLE
Album

### ISSUE THREAD

**Issue by An0nima** [Sorrow446/Qo-DL#6]
Please download this album in mp3 and flac format for me, will be eternally grateful.
`https://play.qobuz.com/album/jkq324obxdkrb?pt=57137291`
`https://www.qobuz.com/gb-en/album/controlalo-desde-lejos-david-moleon/jkq324obxdkrb`

**Comment by Sorrow446** [comment]
Irrelevant. Not an issue.

**Comment by An0nima** [comment]
I'm only interested in this album.

**Comment by An0nima** [comment]
@Sorrow446
I'm only interested in this album.
