### ISSUE TITLE
Fix GUI.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/Qo-DL#60]
Simple fix. Replace no longer functional app ID / secret with working ones or take them from config file.

**Comment by Superhackman** [comment]
?

**Comment by Superhackman** [comment]
I don't understand, what file should I modify to make qo-dl gui work?

**Comment by Sorrow446** [comment]
Could you make it so your GUI takes the app & secret from the ones in the user's config file?

**Comment by Superhackman** [comment]
@Sorrow446 
mmm the bad news is that it doesn't work for me when i add the file to the
 GUI when the config.ini file is already configured and when searching for some music it is blank and no results appear, and I even tried with the application open to see the GUI will show me the results, but nothing, it doesn't work.
![image](https://user-images.githubusercontent.com/27593140/62013602-6cad9900-b15a-11e9-9981-5cdffcb7cf77.png)

![image](https://user-images.githubusercontent.com/27593140/62013626-aed6da80-b15a-11e9-9883-3e9b46b57ca2.png)

![image](https://user-images.githubusercontent.com/27593140/62013642-f0678580-b15a-11e9-8ea2-1973c6939d60.png)

**Comment by Superhackman** [comment]
?

**Comment by Superhackman** [comment]
help

**Comment by pedrothelion** [comment]
Hello, I add app id, app secret email and password in config.ini but nothing happen when try to download. Is this gui working? Thanks for helping me!

**Comment by Sorrow446** [comment]
Fixed. Grab in releases section.
