### ISSUE TITLE
Error in latest 5c Qo-DL.py

### ISSUE THREAD

**Issue by shivsah** [Sorrow446/Qo-DL#66]
`Input Qobuz Player or Qobuz store URL:https://open.qobuz.com/track/61592873
The API did not return a(n) Composer. Tag will be left empty.
Traceback (most recent call last):
  File "Qo-DL.py", line 719, in <module>
    init()
  File "Qo-DL.py", line 701, in init
    rip(album_id, isTrack, session, comment, formatId, alcovs, downloadDir, fp, keepCover)
  File "Qo-DL.py", line 217, in rip
    and metadata["VERSION"] not in metadata["TITLE"] \
TypeError: 'in <string>' requires string as left operand, not NoneType`

**Comment by TitouanGendron** [comment]
Hi! I just posted a pull request that may fix your problem.

**Comment by 0OOOOOOO0** [comment]
Is it the same problem?
https://github.com/Sorrow446/Qo-DL/issues/63#issuecomment-513625274

**Comment by TitouanGendron** [comment]
no it is not.

I can't have the same bug as you, but you can try to add a 'try' before line 127, then add 
`except KeyError:`
    `pass`
after the line
`audio[id3tag.__name__] = id3tag(encoding=3, text=value) `

![Capture d’écran_2019-07-22_12-07-48](https://user-images.githubusercontent.com/40029431/61624694-678fac00-ac79-11e9-968f-eda1b1c68620.png)

then tell us if it solved your problem

**Comment by 0OOOOOOO0** [comment]
@TitouanGendron
>   File "C:\Program Files\Qo-DL\Qo-DL.py", line 128
    id3tag = legend[tag]
                       ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by TitouanGendron** [comment]
Make sure you used tabs instead of spaces. Some text editors insert spaces when you type tab.

**Comment by 0OOOOOOO0** [comment]
@TitouanGendron 
You can paste the full code Qo-DL.py please.

**Comment by TitouanGendron** [comment]
for tag, value in metadata.items():
		if value:
			try:
				id3tag = legend[tag]
				audio[id3tag.__name__] = id3tag(encoding=3, text=value)
			except KeyError:
				pass
	audio.save(filename, 'v2_version=3')

**Comment by 0OOOOOOO0** [comment]
@TitouanGendron

I thank you for your great help but I'm sorry to tell you another error, I was referring to the complete Qo-DL.py code if you can do the favour of publishing it. 

>   File "C:\Program Files\Qo-DL\Qo-DL.py", line 126
    if value:
     ^
IndentationError: expected an indented block

**Comment by DashLt** [comment]
My apologies, fixed in the latest commit.
@TitouanGendron what pull request?
