### ISSUE TITLE
An other bug 

### ISSUE THREAD

**Issue by TitouanGendron** [Sorrow446/Qo-DL#68]
I still have problems with the last version of Qo-DL.py : 

Traceback (most recent call last):
  File "Qo-DL.py", line 717, in <module>
    init()
  File "Qo-DL.py", line 699, in init
    rip(album_id, isTrack, session, comment, formatId, alcovs, downloadDir, fp, keepCover)
  File "Qo-DL.py", line 185, in rip
    ("thumbnail", "small", "large")[alcovs]
TypeError: tuple indices must be integers or slices, not str

it is fixed by replacing lines 184, 185 and 186 

		album_cover_url = albumMetadata["image"][
			("thumbnail", "small", "large")[alcovs]
		]

by 

		album_cover_url = albumMetadata["image"][alcovs]

as alcovs directly takes "thumbnail", "small" or  "large" values and is not an integer.

I tried to make a pull request for this but something happened and  it disappeared. Sory for being a noob with github, it is the first time I use this website.

**Comment by DashLt** [comment]
Alcovs is an integer, or rather should be. Do not put quotes around it in the config file.
