### ISSUE TITLE
Customize tags

### ISSUE THREAD

**Issue by 0OOOOOOO0** [Sorrow446/Qo-DL#69]
Is it possible to customize "URL" and "COPYRIGHT" tags?

Example:
URL: https://qobuz.com
COPYRIGHT: Downloaded with the Qo-DL program

**Comment by DashLt** [comment]
You can sorta achieve the former in the Comment tag by changing that value to "url". Customizable tags may be a good idea for the future, though.

**Comment by 0OOOOOOO0** [comment]
If I know it but the recommended thing would be that it was in the URL tag and not in comment, by the way, he still doesn't put the album year on the tag.

**Comment by DashLt** [comment]
The latter has been fixed.

**Comment by 0OOOOOOO0** [comment]
Thank you for updating "YEAR" tag in the mp3 it and sorry for the inconvenience, all that remains is to customize the "COPYRIGHT" and "URL" tags (on the URL tag and not on comment tag).

**Comment by 0OOOOOOO0** [comment]
Do not bother in the customization of tags, there are many albums in qobuz that its information is wrong, in some albums do not even have the remix, the recommended thing would be for the customization of tags the script of stevehero for the program mp3tag, this issue has been resolved, please close it.

`https://community.mp3tag.de/t/beatport-com-wss-by-stevehero-release-single-track-artwork-tagging/12568`
