### ISSUE TITLE
Qo-DL GUI cannot find specific album

### ISSUE THREAD

**Issue by annnder** [Sorrow446/Qo-DL#7]
Qo-DL GUI cannot find specific album:

https://play.qobuz.com/album/movo40lyc8zdb

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/54930848-511a5380-4f18-11e9-8e86-1a92bd6108ed.png)

As you can see, it finds specific album and the 1 track on the album correctly.
Are you using VPN?
What's the country IP?

**Comment by annnder** [comment]
> As you can see, it finds specific album and the 1 track on the album correctly.
> Are you using VPN?
> What's the country IP?

I am not using any VPN, my country IP is Poland, my Qoubuz registration account country is the UK.
Also, I can stream this album without any problems on the Qoubuz web player.

Also, when I am using Qo-DL_x64.exe directly, I have this error: 

>  found (404). Bad URL or a proxy / VPN is needed. If you're already connected  to a proxy, try a different one in a different country and make sure it's https, and not http. Returning to URL input screen...

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/54958688-dd4b6b80-4f56-11e9-9202-2276ebb6bbd5.png)

My Qobuz registration account country is DE.
I am not using any VPN, my country IP is NL.

**Comment by Sorrow446** [comment]
Hello.
This problem isn't because of Qo-DL or its GUI. Your account's region doesn't matter in this case, but the location of your IP address does. A temporary VPN or proxy is needed. Qo-DL supports the use of them, but the GUI doesn't. Single track downloading is supported, just to correct. I'm still not sure why the API does this.
