### ISSUE TITLE
Problem with confing,ini

### ISSUE THREAD

**Issue by darkangel2325** [Sorrow446/Qo-DL#75]
When i try to start Qo-DL it gives me a warning, but i don't know what i must do with this, can someone help? this is the warning.
![Immagine](https://user-images.githubusercontent.com/51389134/61886663-67551200-af00-11e9-9d01-298ebf6242d2.png)
I don't know what to write in this naming scheme

**Comment by DashLt** [comment]
Sorry, please use this config.ini until the next update: https://github.com/Sorrow446/Qo-DL/blob/R5C/config.ini
