### ISSUE TITLE
missing namingScheme.

### ISSUE THREAD

**Issue by khazz89** [Sorrow446/Qo-DL#76]
This is driving me crazy, any ideas of how to fix it?
I tried to fill the line "namingScheme = "" " with the number 2 or 1 without any results. It always resets to "" (empty) after executing "Qo-DL_x86"
![Untitled](https://user-images.githubusercontent.com/53316165/61912531-02012100-af00-11e9-894a-401712892776.jpg)

**Comment by mygalaxys9** [comment]
> This is driving me crazy, any ideas of how to fix it?
> I tried to fill the line "namingScheme = "" " with the number 2 or 1 without any results. It always resets to "" (empty) after executing "Qo-DL_x86"
> ![Untitled](https://user-images.githubusercontent.com/53316165/61912531-02012100-af00-11e9-894a-401712892776.jpg)

how you fix this ?

**Comment by khazz89** [comment]
This bug only is for R5c version, so you just need to replace the code in config.ini for this code.

[Main]
;Program should now obtain these automatically
;If autoobtaining is broken, try https = //thoas.feralhosting.com/sorrow/Qobuz-DL/App.txt
appId = ""
appSecret = ""
email = ""
;5 = 320 kbps MP3, 6 = 16-bit FLAC, 7 = 24-bit / =< 96kHz FLAC, 27 = best avail - 24-bit / >96 kHz =< 192 kHz FLAC.
formatId = "27"
;Password. Md5 hashed or plain text.
password = ""
;1 = "01. ", 2 = "01 -"
namingScheme = "1"
;0 = 50x50, 1 = 230x230, 2 = 600x600, 3 = max
;-1 = no cover fetched
coverSize = "3"
;Specify where to download tracks to, "Qo-DL Downloads" by default
downloadDir = "Qo-DL Downloads"
;Leave folder.jpg in album dir, Y or N. Not usable with Qobuz-DL_Playlist.
keepCover = "n"
useProxy = "N"
;<IP address> = <port> Must be https. This can't be used to bypass Qobuz's region restrictions for track downloading.
proxy = ""
;Skip check to see if password is a valid MD5 hash. "Y" or "N".
skipPwHashCheck = "n"
checkForUpdates = "y"

[Tags]
ALBUM = "y"
ALBUMARTIST = "y"
ARTIST = "y"
;Custom comment, leave as "" for none. You can also input "url" to write the album url to the field.
COMMENT = ""
COMPOSER = "y"
COPYRIGHT = "y"
DATE = "y"
GENRE = "y"
;id3 doesn't support the organization (record label) field, so the publisher field will be used instead for mp3s.
ORGANIZATION = "y"
TITLE = "y"
;The track total has to be stored inside the track field for mp3s ("<curtr>/<trtotal>") because...
;id3 doesn't support the tracktotal/totaltracks fields like vorbis does. Track will include the track total when used for mp3s.
TRACKNUMBER = "y"
TRACKTOTAL = "y"
;Extended performer data. Useful only for classical music. Only works with FLAC
;Contains more specific things like who played what instrument, the conductor, recording arranger, etc.
;This *will need* to be manually edited. If you don't know if you need this, you don't.
extendedMetadata = "n"
