### ISSUE TITLE
5d namingScheme = ""

### ISSUE THREAD

**Issue by mygalaxys9** [Sorrow446/Qo-DL#81]
How fix this ? namingScheme = "" DL 5d

The following required fields in your config file are missing: namingScheme.
Wrote missing field(s) to config file. Please fill them in.
Exiting...

**Comment by khazz89** [comment]
5d? or 5c?
https://github.com/Sorrow446/Qo-DL/issues/76

**Comment by DashLt** [comment]
https://github.com/Sorrow446/Qo-DL/blob/R5C/config.ini
Use this config file until the next update.

**Comment by mygalaxys9** [comment]
> 5d? or 5c?
> #76

5d , i mean new releases 1 days ago ?

**Comment by mygalaxys9** [comment]
> https://github.com/Sorrow446/Qo-DL/blob/R5C/config.ini
> Use this config file until the next update. Duplicate of #75 anyway.

Was update 1 days ago alright?

**Comment by mygalaxys9** [comment]
See this 
https://github.com/Sorrow446/Qo-DL/blob/master/config.ini

By, source 5d

**Comment by mygalaxys9** [comment]
![Screenshot_20190801-052115_Samsung Internet](https://user-images.githubusercontent.com/52847534/62252182-474fb200-b41c-11e9-9b43-65ddc4206cc3.jpg)
