### ISSUE TITLE
Qo-DL GUI don't download anything

### ISSUE THREAD

**Issue by pedrothelion** [Sorrow446/Qo-DL#82]
Hello, anyone can explain me why I'm not able to download anything?
I add app id, app secret email and password in config.ini but nothing happen when try to download. Box search didn't return anything. Is this gui working?
Thanks for helping me!

**Comment by khazz89** [comment]
Are you using a VPN?
Have you tried using "Qo-DL_x86.exe"?
Gui does not work for me, i've always downloaded throught Qo-DL_x86.exe.

**Comment by pedrothelion** [comment]
No VPN, added Qo-DL_x86.exe or Qo-DL_x64.exe but does not work!

**Comment by khazz89** [comment]
As long as i know a VPN is a must, unless you live in france, germany, or some country in europe.
It does work for me.
![image](https://user-images.githubusercontent.com/53316165/62241167-44ae7780-b39e-11e9-9c4a-3cbdcbe64681.png)
![image](https://user-images.githubusercontent.com/53316165/62241176-4841fe80-b39e-11e9-83e6-343f8f804b00.png)

**Comment by khazz89** [comment]
I am ussing a VPN to Germany by the way (windscribe)

**Comment by pedrothelion** [comment]
Are you not using the GUI. Right?

**Comment by pedrothelion** [comment]
I'm trying a VPN to Germany with dedicated IP (NordVPN) but didn't work.

**Comment by khazz89** [comment]
Nop, i'm not ussing GUI, test it with Windscribe VPN to germany, i've tried with Surfshark with out any results, only Windscribe works for me.

**Comment by pedrothelion** [comment]
Kindly can you guide me step-by-step on how to download throught Qo-DL_x86.exe?

**Comment by khazz89** [comment]
https://github.com/Sorrow446/Qo-DL/releases

**Comment by khazz89** [comment]
-Download Windscribe and connect it to germany, you can try a free acount just for test
-Fill your "config.ini" with your email and password
-Download the last compiled "Qo-DL_x86.exe" over here and copy it to the "Qo-DL-master" folder.
https://github.com/Sorrow446/Qo-DL/releases
-Execute "Qo-DL_x86.exe" and try
If it shows you a bug or error post it here.

**Comment by DashLt** [comment]
@pedrothelion please join our discord or add either Sorrow or me (look in the README)
@khazz89 please join as well so I can thank you for being helpful

**Comment by pedrothelion** [comment]
Thank you. It works!!!
Can this method download albums on bulk?

**Comment by pedrothelion** [comment]
@DashLt where's the discord link?

**Comment by DashLt** [comment]
https://discord.gg/EFeFph
This is a temporary link that will be killed shortly.

**Comment by DashLt** [comment]
@pedrothelion check the readme
