### ISSUE TITLE
Some HD albums can't download with Qo-DL R5c

### ISSUE THREAD

**Issue by pedrothelion** [Sorrow446/Qo-DL#83]
Qo-DL R5c doesn't work on some HD albums.
Signed in successfully into my Studio account but when paste the qobuz link it return cover only. Any idea?

**Comment by DashLt** [comment]
Does it exit after downloading?

**Comment by khazz89** [comment]
Link of the album please to check

**Comment by pedrothelion** [comment]
I noticed that issue will be fixed with 5d release. When it will be out?

**Comment by DashLt** [comment]
Now!
