### ISSUE TITLE
Some albums are missing tag.

### ISSUE THREAD

**Issue by pedrothelion** [Sorrow446/Qo-DL#86]
Uisng R5c (master or GUI) some songs are missing the tag name.
This for example: https://play.qobuz.com/album/3614591296475

Please fix this issue. Thank you!

![missing_tag](https://user-images.githubusercontent.com/6648848/62353135-32514c80-b50a-11e9-87d1-d184e2cf88bf.jpg)

**Comment by DashLt** [comment]
Please retest with R5d and screenshot any errors if they appear

**Comment by pedrothelion** [comment]
Tested with R5d but is worse than before:

![missing_tag_5d](https://user-images.githubusercontent.com/6648848/62378471-2c2c9180-b545-11e9-9a23-964661da9aa8.jpg)

Failed to rename track ERROR!

![ScreenHunter 41](https://user-images.githubusercontent.com/6648848/62378531-4c5c5080-b545-11e9-8f7f-a87951c2d887.jpg)

Another stange issue:
When it finished to download all album tracks the process restart again into an infinite loop.

**Comment by DashLt** [comment]
See where it says "Failed to rename track"? The name of the song is too long for Windows. You'll have to rename it yourself.

**Comment by pedrothelion** [comment]
Pardon but I don't think that's the problem.
Here's the same album downloaded with R5c

![R5C](https://user-images.githubusercontent.com/6648848/62382797-a1509480-b54e-11e9-9a6e-c7fca4ebe240.jpg)

You can notice that tracks 8, 9, 10, 11 was tagged properly, while with R5D the same tags are missing. Same PC for boths.
