### ISSUE TITLE
Downloading restart again into a loop! R5d

### ISSUE THREAD

**Issue by pedrothelion** [Sorrow446/Qo-DL#87]
Strange issue on R5d:

When it finished to download all album tracks the process restart again into an infinite loop so I need to stop the promt abruptly!!

**Comment by DashLt** [comment]
Can you send a link to the album?

**Comment by pedrothelion** [comment]
This: https://open.qobuz.com/album/0822252227826

**Comment by DashLt** [comment]
The album works for me with the uncompiled version. Will try with the compiled version on windows.

**Comment by DashLt** [comment]
Ok, this works for me. Can you please join the discord so I can help you a little more?

**Comment by DashLt** [comment]
I'm awaiting someone who also has this issue.

**Comment by Asutaroto** [comment]
Confirmed. There is such a problem on version 5d.

https://filebin.net/n1o03ja0k1s708n2/20190809_163014.mp4?t=1o1w0n69

**Comment by DashLt** [comment]
Ah, thank you for the video. I wonder if this is an issue with the GUI.

**Comment by DashLt** [comment]
Found the issue, I broke passing URLs on the command line when I fixed track lists. What else is new? Fix incoming.
