### ISSUE TITLE
DOWNLOAD IS SLOW

### ISSUE THREAD

**Issue by ZPH666666** [Sorrow446/Qo-DL#93]
Can I show the download link?  Because the download is very slow, it will be better to change IDM.

**Comment by ZPH666666** [comment]
I am come from china，the vpn is slow

**Comment by DashLt** [comment]
Unfortunately, this is not possible, as Qobuz needs a specific header when downloading. The download manager we use uses the same technology as IDM; you are unlikely to get any performance improvements.
