### ISSUE TITLE
Can you add a cover to the downloaded song?

### ISSUE THREAD

**Issue by ZPH666666** [Sorrow446/Qo-DL#94]
Can you add a cover to the downloaded song?

**Comment by khazz89** [comment]
The song is always downloaded with the cover art inside of the file as you can see in the next picture, i didn't add anything, just downloaded from Qobuz.
![image](https://user-images.githubusercontent.com/53316165/62591440-2e6c5400-b895-11e9-92a2-93cffd0545ac.png)

**Comment by DashLt** [comment]
This is correct. Make sure that albumCoverSize isn't set to -1 in your config.ini.
