### ISSUE TITLE
Download the track, use foobar2000 to right click on the property and recode it! How can I set it without being re-encoded?

### ISSUE THREAD

**Issue by zzxhll** [Sorrow446/Qo-DL#99]
Download the track, use foobar2000 to right click on the property and recode it! How can I set it without being re-encoded?
![1](https://user-images.githubusercontent.com/53909508/62716395-b472d100-ba34-11e9-86f2-1dfcdd2a0ab7.jpg)
In the same album, the above picture is an album download re-encoded by Qo-DL. The image below is not downloaded by Qo-DL and will not be re-encoded.
![1](https://user-images.githubusercontent.com/53909508/62716829-63171180-ba35-11e9-9c9e-f76b86a35b1e.jpg)

**Comment by zzxhll** [comment]
How to set the Qo-DL download without re-encoding the track?

**Comment by khazz89** [comment]
> How to set the Qo-DL download without re-encoding the track?

What's the point? It's still a lossless file.

**Comment by Sorrow446** [comment]
This isn't really relevant to Qo-DL. See [this](https://xiph.org/flac/documentation_tools_metaflac.html). Make sure you keep the padding enabled.

To clarify, Qo-dl DOES NOT re-encode any tracks. The only way they are altered is by writing their tags and covers.

**Comment by zzxhll** [comment]
Writing tags and covers will change, Qo-DL-R5d where to cancel loading the cover? What settings are needed to cancel the loading of the cover, thank you!

**Comment by zzxhll** [comment]
How to change the image size to 600X600? The Qo-DL-R5d is the largest size.

**Comment by zzxhll** [comment]
It is useless to modify the parameters in config.ini with Qo-DL-R5d. Is the next version of config.ini custom modified?
